### ISSUE TITLE
Adaptive Scalable Texture Compression

### ISSUE THREAD

**Issue by KOLANICH** [KOLANICH/KSFGHAction.py#1]
```yaml
meta:
  id: adaptive_scalable_texture_compression
  title: Adaptive Scalable Texture Compression
  application: OpenGL
  xref:
    wikidata: Q4680713

doc: |
  A format for textures.

doc-ref:
  - https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_texture_compression_astc_hdr.txt
```
